version: "3.9"
services:
  database:
    build:
      context: ./database
    container_name: nativeip-db
    volumes:
      - nativeip-db-volume:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nativeip-bridge
    ports:
      - 3031:3306
  backend:
    build:
      context: ./backend
    container_name: nativeip-api
    networks:
      - nativeip-bridge
    ports:
      - 3030:3030
    depends_on:
      - database
    volumes:
      - nativeip-api-volume:/api
  frontend:
    build:
      context: ./frontend
    container_name: nativeip-app
    networks:
      - nativeip-bridge
    ports:
      - 3032:3032
    depends_on:
      - database
      - backend
    volumes:
      - nativeip-app-volume:/app
networks:
  nativeip-bridge:
    driver: bridge
volumes:
  nativeip-db-volume:
  nativeip-api-volume:
  nativeip-app-volume: